project:
  type: website
  output-dir: docs
  
website:
  title: "Litta Jose Thottam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - name: mail
        href: "mailto:josethottamlitta@gmail.com"
      - icon: linkedin
        href: https://www.linkedin.com/in/litta-thottam-12a223193/
      - icon: github
        href: https://github.com/Littajosethottam/My_Project
      - name: CV
        href: CV.pdf
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Litta Jose Thottam"

format:
  html:
    theme: cerulean
    toc: true

editor: source

